# Generated by Django 2.0.9 on 2019-01-27 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('user', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('url', models.CharField(max_length=100, verbose_name='网址')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type1', models.CharField(max_length=50, verbose_name='目录')),
                ('type2', models.CharField(max_length=50, verbose_name='分类')),
            ],
        ),
        migrations.AddField(
            model_name='password',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password.Type', verbose_name='分类'),
        ),
    ]
